# Generated by Django 2.2.20 on 2021-04-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obs', models.TextField(blank=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.Ativo')),
            ],
        ),
    ]
