# Generated by Django 2.2.20 on 2021-04-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaAtivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('valor_venda_cota', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade_cotas', models.IntegerField(verbose_name='Quantidade de Cotas')),
                ('valor_patrimonial_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_mercado_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo_venda', models.TextField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.Ativo')),
            ],
        ),
    ]
