# Generated by Django 2.2.20 on 2021-04-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatosRelevantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('fato', models.TextField(max_length=200, verbose_name='Fato Relevante')),
                ('solucao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Solução')),
                ('solucionado', models.BooleanField(verbose_name='Solucionado')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.Ativo')),
            ],
        ),
    ]
