# Generated by Django 2.2.20 on 2021-04-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, verbose_name='Código')),
                ('nome_amigavel', models.CharField(max_length=60, verbose_name='Nome')),
                ('tipo_ativo', models.CharField(choices=[('A', 'Ação'), ('F', 'Fundo Imobiliario')], max_length=1, verbose_name='Tipo de Ativo')),
                ('gestor', models.CharField(max_length=60)),
                ('data_ipo', models.DateField(verbose_name='Data da IPO')),
                ('valor_ipo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor na IPO')),
                ('segmento', models.CharField(max_length=60)),
                ('data_entrada', models.DateField()),
                ('valor_patrimonial_inicial', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Patrimonial')),
                ('valor_mercado_inicial', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor de Mercado')),
                ('valor_cota_adquirida', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor Cota Adquirida')),
                ('numero_cotas_adquiridas', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantidade de Cotas')),
                ('taxa_b3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Custos B3')),
                ('taxa_liquidacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Taxa Liquidação')),
                ('emolumentos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('motivo_compra', models.TextField(blank=True, null=True, verbose_name='Motivo da Compra')),
                ('regulamento', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
